### ISSUE TITLE
CLUS Documentation - Getting Started Guide

### ISSUE THREAD

**Issue by TylerMuhly** [bcgov/castor#126]
Basic overview of CLUS model framework in .rmd. For new users.

**Comment by TylerMuhly** [comment]
draft completed - needs review

update as-needed

**Comment by KyleLochhead** [comment]
I think a major confusion with the CLUS workflow-- is that we run the dataLoaderCLUS.rmd but it also contains other modules. I'd suggest we rename the dataLoaderCLUS.rmd to build_clus_db.rmd or something similar?
