### ISSUE TITLE
modify disturbanceCalcCLUS to include treed area and total area

### ISSUE THREAD

**Issue by TylerMuhly** [bcgov/castor#301]
The 'disturbance' report from disturbanceCalcCLUS currently reports out total_area as treed area, i.e.,:

Line 161: outPts[treed == 1 & !is.na(critical_hab), .(total_area = uniqueN(.I)), by = c("compartment","critical_hab")]

This limits reporting of percent disturbance as percent of treed area disturbed. Thus, in cases where buffered roads occur, outside of treed areas, the percent disturbance can be >100.

A preferred 'disturbance' report would have total_area reported as:

outPts[!is.na(critical_hab), .(total_area = uniqueN(.I)), by = c("compartment","critical_hab")]

and treed_area reported as:
outPts[treed == 1 & !is.na(critical_hab), .(treed_area = uniqueN(.I)), by = c("compartment","critical_hab")]

This allows flexibility in summarizing by % of total or treed area disturbed.

Note: this will require updating the 'disturbance' tables already in the postgres db.

**Comment by KyleLochhead** [comment]
Closing this --ported to disturbanceCastor.
