### ISSUE TITLE
Support for terra rasters

### ISSUE THREAD

**Issue by KyleLochhead** [bcgov/castor#325]
Start the process of supporting terra

**Comment by KyleLochhead** [comment]
mock function for terra built need to test

**Comment by ElizabethKleynhans** [comment]
If rpostgis is updated to version 1.5.0 or greater the function RASTER_CLIP2 or any function that relies on pgGetRast will not work. This is because pgGetRast relies on rgeos and rgdal and both have been retired. We need to update the raster_clip functions to work around this issue.
