### ISSUE TITLE
fisherABM: Function to create female home ranges in INIT phase

### ISSUE THREAD

**Issue by TylerMuhly** [bcgov/castor#337]
Query to assign 'pixels' in a landscape to a fisher home range (i.e., 'initiate" home ranges).

![fisher_abm_create_HR](https://user-images.githubusercontent.com/34694298/180835171-830b8194-dd3c-4a77-b154-a32f966ee18a.jpg)

**Part 1:** 
FOR EACH individual_id in “agents” table WHERE sex = F 
(ORDER by age to give older animals priority) _could consider this to prioritize older animals_ 

- ASSIGN individual_id and pixelid from the 'agents' table to the 'territories' table; _assign the starting denning habitat pixel to the territories table_

- Calculate distance from the pixelid in the agents table to all denning habitat pixels (query “pixels” table) within the female_search_radius pixels in the “search” table;

- SELECT the closest (and within a minimum distance to ensure clustering of pixels ), unoccupied (i.e., no individual_id assigned to the pixelid in the female territories table), denning habitat pixels, up to where count (denning pixels) > (hr_size * den_target) AND assign the individual_id and pixelid to the female territories table; 

- Calculate distance from the pixelid in the agents table to all resting habitat pixels (query “pixels” table) within the female_search_radius pixels in the “search” table

- SELECT the closest, unoccupied, resting habitat pixels, up to where count (resting pixels) > (hr_size * den_target) AND assign the individual_idand pixelid to the female territories table

- Calculate distance from the pixelid in the agents table to all movement habitat pixels (query “pixels” table) within the female_search_radius pixels in the “search” table

- SELECT the closest, unoccupied , movement habitat pixels, up to where count (movement pixels) > (hr_size * den_target) AND assign the indivdual_id and pixelid to the female territories table

**Part 2:**
IF (hr_size * den_target) < count (SELECT pixelid’s that belong to the individual_id in the “territories” table and are denning habitat in the “pixels” table)
OR
IF (hr_size * rest_target) < count (SELECT pixelid’s that belong to the individual_id in the “territories” table and are resting habitat in the “pixels” table)
OR
IF (hr_size * move_target) < count (SELECT pixelid’s that belong to the individual_id in the “territories” table and are movement habitat in the “pixels” table)
THEN
Remove rows with individual_id from the “territories” and “agents” table
ELSE
Calculate d2_score by querying the ‘pixels’ table using the pixelids for the individual_id in the female territories table

**Model Parameters**
- female_search_radius: maximum search radius, in metres, that a female fisher could ‘search’ to establish a territory; _(year?, summer/fall?; or use max diameter of a territory?)_
- den_target : desired proportion of a home range that is denning habitat
- rest_target : desired proportion of a home range that is resting habitat
- move_target : desired proportion of a home range that is movement habitat

**Comment by TylerMuhly** [comment]
Update Aug. 4:

Currently the fxn grabs all habitat in the search area, then checks to see if it meets the min threshold. 

Need to add a step here to check the habitat configuration, i.e., we need to remove parts of home ranges where the habitat patches are too small in size and too far form neighbouring patches. 

Need to assign population (boreal, columbian) to each pixels - what data to use? Need this to define population appropriate survival, reproduction rates, etc

**Comment by joburgar** [comment]
Note Aug. 8:

Review of female fisher home ranges suggests adults can persist when ~half of home range does not consist of denning, resting and/or movement habitat. The proportion of the combined habitat characteristics within a home range: min = 0.15; mean = 0.51; max = 0.84; sd =0.17. Visual examination of data suggests that female fishers with home ranges in the Sub-Boreal Dry and Sub-Boreal Moist (Columbian population) had larger home ranges with smaller proportions of necessary habitat; perhaps they need larger areas to ensure a minimum amount of suitable habitat in a sea of unsuitable habitat.

**Comment by joburgar** [comment]
Note Aug 10:

Spoke with Scott Yaeger - noted that fisher have a "50 m dash distance" so we should have core habitat (denning, resting, movement) with at most a 1 pixel gap between the habitat pixels. Although maybe we could trial 2 pixels if not creating a large enough home range with the 1 pixel gap rule. Scott also recommended looking at the open areas model as an option for how much "open" habitat fisher will include in their HR but that might make things even more complex if we have to add in a new raster layer(s).

**Comment by TylerMuhly** [comment]
Updated so that the "spread" rule only allows spread to neighboring 'habitat' pixels (denning, resting, movement) to approximate the "50 m dash distance", i.e., if it's denning, resting, movement then spread probability = 1, or else it's 0.  In the 'test' landscape ~2/3 of agents are able to achieve their target HR size, so it seems like this rule is not going to be too limiting for creating initial home ranges. 

Issues to discuss for this module:
1. Habitat characteristics of agent 'spread' across the landscape, i.e., do we want to refine the rule as defined above?
2. If and how do we allow overlap between fisher territories? The 'spread' algorithm can be set to allow or not allow overlap. It seems that monitored fisher territories overlap, but we need to define the overlap 'rules' (e.g., where and how much overlap is allowed)

**Comment by TylerMuhly** [comment]
Overlaps between agents need to be resolved in a way that doesn't underestimate the capacity of the habitat to support fisher. One option is to 'saturate' the landscape with agents so that many territories are formed, then remove those that don't meet overlap (and other) rules. Another option is to 'burn-in' the number of fisher, but that could be problematic if the landscape is in a very poor initial state (all fisher would die). Will try the 'saturation' approach initially.

**Comment by TylerMuhly** [comment]
Will need to circle back to how to deal with fisher territories that overlap habitat zones. Boreal and Columbian have very different territory sizes, so if a territory size is assigned based on starting pixel, but that pixel is on the edge of both zones, it could over or underestimate the territory size. One option could be to only allow it to spread to its starting zone. Need some more thought.

**Comment by joburgar** [comment]
> 

I reviewed the home range area mean and SD per fisher habitat extension zone and the SD is wide enough that it might all come out in the wash - if a home range was set at the high end of the Sub-boreal zones but most of the range was actually in Dry Forest or Boreal then it might not make the most sense, but if it's on the low end, no issue. Same goes with the other extreme. Means are ~30 km2 for Boreal / Dry Forest and ~45 km2 for the Sub-boreal zones.

**Comment by joburgar** [comment]
> Overlaps between agents need to be resolved in a way that doesn't underestimate the capacity of the habitat to support fisher. One option is to 'saturate' the landscape with agents so that many territories are formed, then remove those that don't meet overlap (and other) rules. Another option is to 'burn-in' the number of fisher, but that could be problematic if the landscape is in a very poor initial state (all fisher would die). Will try the 'saturation' approach initially.

I checked in with Rich and Scott - from Weir et al. 2009 and Lofroth 2010 the consensus is that animals do overlap where prey are abundant, but not very much generally, and typically only the periphery of their home range. It gets a bit complicated but biologically speaking it would be best if the perimeter 5% of their home range (i.e., not the core) allows for overlap of movement and resting habitat but there is never overlap of denning. Overlap is likely a function of temporal avoidance. Is it possible to create a "core" and then a "periphery" home range? The core would contain denning, resting and movement habitat. The periphery only resting and movement. The core would not allow overlap and the periphery would.

**Comment by TylerMuhly** [comment]
> > Overlaps between agents need to be resolved in a way that doesn't underestimate the capacity of the habitat to support fisher. One option is to 'saturate' the landscape with agents so that many territories are formed, then remove those that don't meet overlap (and other) rules. Another option is to 'burn-in' the number of fisher, but that could be problematic if the landscape is in a very poor initial state (all fisher would die). Will try the 'saturation' approach initially.
> 
> I checked in with Rich and Scott - from Weir et al. 2009 and Lofroth 2010 the consensus is that animals do overlap where prey are abundant, but not very much generally, and typically only the periphery of their home range. It gets a bit complicated but biologically speaking it would be best if the perimeter 5% of their home range (i.e., not the core) allows for overlap of movement and resting habitat but there is never overlap of denning. Overlap is likely a function of temporal avoidance. Is it possible to create a "core" and then a "periphery" home range? The core would contain denning, resting and movement habitat. The periphery only resting and movement. The core would not allow overlap and the periphery would.

If only 5% overlap than I suggest we make overlap = F rather than try to find a function to allow overlap on the edges; at best 5% will only squeeze in 1 extra HR per 19 HR's, I think. Not sure that overlap needs to be accounted for.

**Comment by TylerMuhly** [comment]
> Note Aug. 8:
> 
> Review of female fisher home ranges suggests adults can persist when ~half of home range does not consist of denning, resting and/or movement habitat. The proportion of the combined habitat characteristics within a home range: min = 0.15; mean = 0.51; max = 0.84; sd =0.17. Visual examination of data suggests that female fishers with home ranges in the Sub-Boreal Dry and Sub-Boreal Moist (Columbian population) had larger home ranges with smaller proportions of necessary habitat; perhaps they need larger areas to ensure a minimum amount of suitable habitat in a sea of unsuitable habitat.

Experimenting with this by idea allowing spread into non-habitat pixels....

**Comment by TylerMuhly** [comment]
> > Note Aug. 8:
> > Review of female fisher home ranges suggests adults can persist when ~half of home range does not consist of denning, resting and/or movement habitat. The proportion of the combined habitat characteristics within a home range: min = 0.15; mean = 0.51; max = 0.84; sd =0.17. Visual examination of data suggests that female fishers with home ranges in the Sub-Boreal Dry and Sub-Boreal Moist (Columbian population) had larger home ranges with smaller proportions of necessary habitat; perhaps they need larger areas to ensure a minimum amount of suitable habitat in a sea of unsuitable habitat.
> 
> Experimenting with this by idea allowing spread into non-habitat pixels....

allowing a spread prob of 0.19 into non-habitat pixels achieves an average 55% prop of home range is habitat (after removing cases where habitat was less than 15%). 0.18 was <50% and 0.2 was ~60%. Not sure if this 'magic number' needs to be tuned to other areas.

**Comment by TylerMuhly** [comment]
> Update Aug. 4:
> 
> Currently the fxn grabs all habitat in the search area, then checks to see if it meets the min threshold.
> 
> Need to add a step here to check the habitat configuration, i.e., we need to remove parts of home ranges where the habitat patches are too small in size and too far form neighbouring patches.
> 
> Need to assign population (boreal, columbian) to each pixels - what data to use? Need this to define population appropriate survival, reproduction rates, etc

COMPLETE - pop added and configuration dealt with through spread algorithm

**Comment by TylerMuhly** [comment]
Denning habitat is typically the limiting factor in terms of habitat proportions (although there are some low proportion resting and movement cases). 

Need to decide on whether to use amount or proportion to define the minimums, and what the minimum amount/proportion we want to use. These can be user defined, but if they are set too high, it will result in too few fisher on the landscape.

E.g., In the Williams Lake TSA, if I set proportions at the mean value (den = 0.1, rest = 0.26 and move = 0.36) it resulted in no fisher; setting proportions at the min value (den = 0.003, rest = 0.028 and move = 0.091) resulted in 94 fisher. Note: estimated # fisher for Williams Lake from FETA mapper is 61 .

I'm thinking we use the min value as the default threshold targets. The user can set larger thresholds, but we should note this could be fairly restrictive.

**Comment by KyleLochhead** [comment]
see #430
