### ISSUE TITLE
fisherABM: Dispersal Function

### ISSUE THREAD

**Issue by TylerMuhly** [bcgov/castor#340]
Function to "disperse" fisher that either: 1. aren't able to improve their habitat quality, or, 2. are mature kits (1 year old) in a home range occupied by its mother. 

![fisher_abm_disperse](https://user-images.githubusercontent.com/34694298/180847599-9212c54e-84d1-4c62-b563-8d701b7aba54.jpg)

**Part 1:**
SELECT individual_id WHERE pixelid IS NOT NULL AND AGE = 1 (i.e., individual is a mature kit in a home range occupied by its mother) OR habitat targets not met in (i.e., need to call this function from the update home range function)

- Calculate distance from the pixelid in the agents table to all denning habitat pixels (query “pixels” table) within the max_female_dispersal_dist 

- SELECT the closest l(with a minimum distance to other denning pixels to ensure clustering of pixels ), unoccupied (i.e., no individual_id assigned to the pixelid in the female territories table), denning habitat pixel, up to where count (denning pixels) > (hr_size * den_target) AND where distance to the pixelid in the agents table is greater than the female_search_radius, AND assign the individual_id and pixelid to the female territories table AND randomly assign one of the denning habitat pixels to pixelid;
_need to identify a cluster of pixels, not a single pixel_

- Calculate distance from the pixelid in the agents table to all denning habitat pixels (query “pixels” table) within the female_search_radius pixels in the “search” table

- SELECT the closest, unoccupied (i.e., no individual_id assigned to the pixelid in the female territories table), denning habitat pixels, up to where count (denning pixels) > (hr_size * den_target) AND assign the individual_id and pixelid to the female territories table

- Calculate distance from the pixelid in the agents table to all resting habitat pixels (query “pixels” table) within the female_search_radius pixels in the “search” table

- SELECT the closest, unoccupied, resting habitat pixels, up to where count (resting pixels) > (hr_size * rest_target) AND assign the individual_id and pixelid to the female territories table

- Calculate distance from the pixelid in the agents table to all movement habitat pixels (query “pixels” table) within the female_search_radius pixels in the “search” table

- SELECT the closest, unoccupied, movement habitat pixels, up to where count (movement pixels) > (hr_size * move_target) AND assign the indivdual_id and pixelid to the female territories table

**Part 2:**
IF (hr_size * den_target) < count (SELECT pixelid’s that belong to the individual_id in the “territories” table and are denning habitat in the “pixels” table)
OR
IF (hr_size * rest_target) < count (SELECT pixelid’s that belong to the individual_id in the “territories” table and are resting habitat in the “pixels” table)
OR
IF (hr_size * move_target) < count (SELECT pixelid’s that belong to the individual_id in the “territories” table and are movement habitat in the “pixels” table)
THEN
Remove rows with individual_id from the “territories” and “agents” table
ELSE
Calculate d2_score by querying the ‘pixels’ table using the pixelids for the individual_id in the female territories table

**Parameters**:
- max_female_dispersal_dist: maximum distance, in metres, a female will disperse to find a territory
- female_search_radius: maximum search radius, in metres, that a female fisher could ‘search’ to establish a territory (year?, summer/fall?; or use max diameter of a territory?)
- den_target : desired proportion of a home range that is denning habitat 
- rest_target : desired proportion of a home range that is resting habitat
- move_target : desired proportion of a home range that is movement habitat

**Comment by TylerMuhly** [comment]
- determine 'spread' area: max area a kit can search to find a territory and min. distance form natal den.
- use movement, other habitat to guide where search area occurs
- use FETA's to re-sample habitat in the spread area and have kit target the 'best'?
- do we need to include barriers as no-spread areas?

**Comment by joburgar** [comment]
From earlier conversations with Rich and for the initial FLEX dispersal function we assumed that female fishers can travel ~35 km in one month. This can be extrapolated to 35*12 = 420 km annually.

I don't think there is any worry about a minimum distance from natal den as long as it's not within an occupied territory, so for a simple rule of thumb of where to start searching perhaps we use the radius of a 30 km2 circle or 3 km from the kits birth pixel, or even better, the radius of the random sized home range of the mom. Make sense?

We also assumed that fishers will start dispersing at 1 yr of age and can only survive without a territory for 2 years (i.e., I killed off all fishers >2 that hadn't yet found a territory). As a side note, we'll have to think about how to keep in the length of time an individual is dispersing to incorporate it into the survival function as home ranges may degrade over time. 

It's a slow and not an elegant function but I tried to have females disperse based on the *best* unoccupied next pixel (although at a much coarser scale): https://github.com/bcgov/FLEX/blob/main/R/disperse_FEMALE.R

**Comment by joburgar** [comment]
Sept 8 update:
Spoke with Rich Weir and there is empirical data that shows one dispersing juvenile fisher travelled ~1200 km in 2 years of dispersing, with a circuitous travel route that only extended ~90 km as the crow flies from her natal den. She died of starvation before she was able to establish a territory.

Rich wasn't adverse to starting with the simple approach of using a distance buffer from the natal den as the polygon to search for home ranges.

So for a general rule, how about we say that in the first year of dispersal a female will search for home ranges within 50 km (radii) of her natal den. If no suitable home ranges are available then in year 2 she searches an area between 50-100 km (or just 100 km from natal den if that's easier computationally) from her natal den. If >1 home ranges are available, choose the home range that is closest to her natal den. If no home ranges are available after 2 years then she dies (that won't be part of the dispersal function, it will be part of the survival function, just noting it here to make sure it's not lost).

**Comment by KyleLochhead** [comment]
Q. Is the survival rate of fishers attempting to disperse related to the habitat they are dispersing in? Probably need to link the habitat the fisher are dispersing in to the survival rate ... the closest "new" denning site might me through a massive open area that poses greater risk of predation or have to navigate a longer distance around the open area expelling more energy.

**Comment by joburgar** [comment]
I would say yes, presumably there would be higher survival when dispersing in great habitat. Without making a complex and computationally intense model, how can we vary survival to habitat?

**Comment by KyleLochhead** [comment]
Well the complex way is to let the dispersing fisher 'spread' around the landscape using the contagion process and the spread probability dictates their ability to find a denning site. This is way too complex as you pointed out. Maybe the simplest way would be to fit a mechanistic relationship with dispersal survival = f(movement habitat) surrounding each individual disperser...we could take the line between a denning site and its current location - as the crow flies; buffer that line by some distance to get an "area of influence". Extract the proportion of movement habitat within that polygon and use that metric to estimate survival of a disperser, maybe distance could also be included: dispersal survival = f(movement habitat, distance)? I would argue this likely needs data to feel confident in the relationship. Another way, albeit slightly more complicated, is to calculate the least cost path between a potential denning site and the fishers current location....the cost would be some expert based cost of navigating each pixel in terms of calories. I would suggest a simplified graph where instead of each 1 ha pixel being the nodes use some larger scale that represents a fishers "area of influence" - say 250 m or something larger? The bigger the better in terms of simplification. The least cost distance would be equal to the number of calories/distance traveled. Allow for expert based opinion on those calories/distance travelled? The actual least cost path of the fisher doesn't really matter (this simplifies the computation) -- just the total distance.... but maybe the path could matter if we also simulate trapper agents?
