### ISSUE TITLE
fisherABM: Survival Function

### ISSUE THREAD

**Issue by TylerMuhly** [bcgov/castor#341]
Function to calculate survival of fisher.

![fisher_abm_survive](https://user-images.githubusercontent.com/34694298/180852892-2cb72a7d-1fd0-4725-945f-5d8a67a8403e.jpg)

**Part 1:**
IF age > max_age THEN remove agent from “agents” table AND from the “territories” table

**Part 2:**
FOR EACH age (i.e., each age class with a unique survival rate) AND individual_id WHERE sex = F 

- Calculate survival_rate = rnorm (1, survival_rate_table::surv_mean WHERE age = xx AND sex = F, survival_rate_table::surv_sd WHERE age = xx AND sex = F)

- Adjust survival_rate = (survival_rate * d2_survival_adj) - based on the d2_score; _adjust survival based on habitat qaulity_

- rbinom (1, 1, survival_rate) AS ‘survived’

- IF survived = 0, remove agent from “agents” table AND from the female “territories” table AND remove agent(s) from “agents” table at the same pixelid (i.e., any kits)

- ELSE update age = age + time_step (year)

**Parameters:**
- The key parameter here is a survival rate table/function that adjust survival based on age and habitat quality
- survival_rate_table : a table of survival rates by age class; mean and sd for each
- max_age : the maximum age of an individual; individual ‘dies’ if greater than this age
- d2_survival_adj: adjustment factor/function for survival based on d2 score
surv_mean

**Comment by joburgar** [comment]
![age_dist_meanprop_plot](https://user-images.githubusercontent.com/24460479/181383772-4ab84a5a-69c0-4eb1-b1c1-84b28cf3319a.PNG)

Rory Fogarty's age distribution data for female fishers, mean proportion by age from 5 different total population sizes  (assuming 71% female : 29% male ratio)

**Comment by joburgar** [comment]
Placeholder for now - thoughts on survival probabilities per year that might work

Age	Surv	SE	Cohort	Rationale
0	1.00	0.00	CFJ	no death first year
1	0.60	0.18	CFJ	SE as per Eric and Rory's estimates
2	0.79	0.09	CFA	SE as per Eric and Rory's estimates
3	0.79	0.09	CFA	SE as per Eric and Rory's estimates
4	0.79	0.09	CFA	SE as per Eric and Rory's estimates
5	0.79	0.17	CFA	2*SE as per Eric and Rory's estimates
6	0.79	0.17	CFA	2*SE as per Eric and Rory's estimates
7	0.79	0.26	CFA	3*SE as per Eric and Rory's estimates
8	0.79	0.26	CFA	3*SE as per Eric and Rory's estimates
9	0.79	0.26	CFA	3*SE as per Eric and Rory's estimates
0	1.00	0.00	BFJ	no death first year
1	0.54	0.19	BFJ	SE as per Eric and Rory's estimates
2	0.86	0.08	BFA	SE as per Eric and Rory's estimates
3	0.86	0.08	BFA	SE as per Eric and Rory's estimates
4	0.86	0.08	BFA	SE as per Eric and Rory's estimates
5	0.86	0.16	BFA	2*SE as per Eric and Rory's estimates
6	0.86	0.16	BFA	2*SE as per Eric and Rory's estimates
7	0.86	0.24	BFA	3*SE as per Eric and Rory's estimates
8	0.86	0.24	BFA	3*SE as per Eric and Rory's estimates
9	0.86	0.24	BFA	3*SE as per Eric and Rory's estimates

**Comment by joburgar** [comment]
![surv_SE_adj_plot](https://user-images.githubusercontent.com/24460479/181649911-9329ab22-749e-4723-a5f4-b18ce9ef912c.PNG)

Adjusting range of uncertainty (SE) based on population distribution with 2* and 3* SE for animals 4-6, and 7-9, respectively.

**Comment by TylerMuhly** [comment]
Survival rates will not be adjusted by habitat quality

**Comment by joburgar** [comment]
Updated survival function (in fisherABM_jo branch) - needs to be finalized to be spades friendly and remove dummy tables (for working through function).

Part 1:
IF age > female_max_age THEN remove agent from “agents” table AND from the “territories” table

Part 2:
FOR EACH individual > 0
Calculate survival = rbinom(n=1, size=1, prob=((Mean - SE) : round(Mean + SE)) # max survival is 1

IF survived = 0, remove agent from “agents” table AND from the female “territories” table 

Keep kits as kits are in same territory but not necessarily still with mom up until 1st birthday and assuming mortality hits in winter, kits may survive. (Give kits a fighting chance)

ELSE update age = age + time_step (year)

**Comment by joburgar** [comment]
Updated to account for juveniles still dispersing after 2 years (will need to discuss with group on how dispersal is being tracked - likely will need to revise).
