### ISSUE TITLE
fisherABM: populate input parameters

### ISSUE THREAD

**Issue by joburgar** [bcgov/castor#347]
Input Parameters: 
n_females = number of females to ‘seed’ the landscape with
female_hr_size_mean = average home range size, ha
female_hr_size_sd = standard deviation of home range size, ha
max_age : the maximum age of an individual; individual ‘dies’ if greater than this age
female_search_radius: maximum search radius, in metres, that a female fisher could ‘search’ to establish a territory (year?, summer/fall?; or use max diameter of a territory?)
den_target : desired proportion of a home range that is denning habitat 
rest_target : desired proportion of a home range that is resting habitat
move_target : desired proportion of a home range that is movement habitat
time_step: time step of model interval, in years
survival_rate_table : a table of survival rates by sex and age class; mean and sd for each
d2_survival_adj: adjustment factor/function for survival based on d2 score
reproductive_age: age that a female reaches sexual maturity
denning_rate_mean: Mean rate or proportion of females that den and give birth to kits
denning_rate_sd: standard deviation of rate or proportion of females that den and give birth to kits
litter_size_mean: Mean number of kits born in a litter
litter_size_sd: standard deviation of the number of kits born in a litter
sex_ratio: the ratio of females to males in a litter
max_female_dispersal_dist: maximum distance, in metres, a female will disperse to find a territory

**Comment by TylerMuhly** [comment]
First draft done; revisit as needed.

**Comment by joburgar** [comment]
Revised as per discussion with Tyler Muhly and Rich Weir. Updates in fisherABM_jb branch as of Aug 8. 2022.

parameters = rbind(
    #defineParameter("paramName", "paramClass", value, min, max, "parameter description"),
    defineParameter("n_females", "numeric", 1000, 0, 10000,
                    "The number of females to 'seed' the landscape with."),    
    defineParameter("female_hr_table", "character", NA, NA, NA,
                    paste0("A table of mean and standard deviation of female fisher home range (territory) sizes in different habitat zones.",
                    "Table with the following headers:",
                    "FHE: the four Fisher Habitat Extension zones: Boreal, Dry Forest, Sub-Boreal moist, Sub-Boreal dry",
                    "Mean_Area_km2: the mean area for female fisher home ranges in km2 for each FHE", 
                    "SD_Area_km2: the sd for female fisher home ranges in km2 for each FHE")),    
    defineParameter("female_max_age", "numeric", 9, 0, 15,
                    "The maximum possible age of a female fisher. Taken from research referenced by Roray Fogart in VORTEX_inputs_new.xlsx document."), 
    defineParameter("female_search_radius", "numeric", 5, 0, 100,
                    "The maximum search radius, in km, that a female fisher could ‘search’ to establish a territory."), 
    defineParameter("den_target", "numeric", 0.10, 0.003, 0.54,
                    "The minimum proportion of a home range that is denning habitat. Values taken from empirical female home range data across populations."), 
    defineParameter("rest_target", "numeric", 0.26, 0.028, 0.58,
                    "The minimum proportion of a home range that is resting habitat. Values taken from empirical female home range data across populations."),   
    defineParameter("move_target", "numeric", 0.36, 0.091, 0.73,
                    "The minimum proportion of a home range that is movement habitat. Values taken from empirical female home range data across populations."), 
    defineParameter("survival_rate_table", "character", NA, NA, NA,
                    paste0("Table of fisher survial rates by sex, age and population, taken from Lofroth et al 2022 JWM vital rates manuscript.",
                           "Table with the following headers:",
                           "Fpop: the two populations in BC: Boreal, Coumbian",
                           "Age_class: two classes: Adult, Juvenile",
                           "Cohort: Fpop and Age_class combination: CFA, CFJ, BFA, BFJ",
                           "Mean: mean survival probability",
                           "SE: standard error of the mean",
                           "Decided to go with SE rather than SD as confidence intervals are quite wide and stochasticity would likely drive populations to extinction. Keeping consistent with Rory Fogarty's population analysis decisions.")),
    defineParameter("d2_reproduction_adj", "function", NA, NA, NA,
                    "Function relating habitat quality to reproductive rate."),
    defineParameter("repro_rate_table", "function", NA, NA, NA,
                    paste0("Table of fisher reproductive rates (i.e., denning rate = a combination of pregnancy rate and birth rate; and litter size = number of kits) by population, taken from Lofroth et al 2022 JWM vital rates manuscript",
                           "Table with the following headers:",
                           "Fpop: the two populations in BC: Boreal, Coumbian",
                           "Param: the reproductive parameter: DR (denning rate), LS (litter size)",
                           "Mean: mean reproductive rate per parameter and population",
                           "SD: standard deviation of the mean reproductive rate per parameter and population")),
    defineParameter("sex_ratio", "numeric", 0.5, 0, 1,
                    "The ratio of females to males in a litter."),
    defineParameter("max_female_dispersal_dist", "numeric", 10, 1, 100,
                    "The maximum distance, in kilometres, a female will disperse to find a territory."),
    defineParameter("timeInterval", "numeric", 1, 1, 20,
                    "The time step, in years, between cacluating life history events (reproduce, updateHR, survive, disperse)."),
    defineParameter(".plots", "character", "screen", NA, NA,
                    "Used by Plots function, which can be optionally used here"),
    defineParameter(".plotInitialTime", "numeric", start(sim), NA, NA,
                    "Describes the simulation time at which the first plot event should occur."),
    defineParameter(".plotInterval", "numeric", NA, NA, NA,
                    "Describes the simulation time interval between plot events."),
    defineParameter(".saveInitialTime", "numeric", NA, NA, NA,
                    "Describes the simulation time at which the first save event should occur."),
    defineParameter(".saveInterval", "numeric", NA, NA, NA,
                    "This describes the simulation time interval between save events."),
    ## .seed is optional: `list('init' = 123)` will `set.seed(123)` for the `init` event only.
    defineParameter(".seed", "list", list(), NA, NA,
                    "Named list of seeds to use for each event (names)."),
    defineParameter(".useCache", "logical", FALSE, NA, NA,
                    "Should caching of events or module be used?")
  ),
