### ISSUE TITLE
error with rsfCLUS when running dataloaderCLUS

### ISSUE THREAD

**Issue by TylerMuhly** [bcgov/castor#89]
**Describe the bug**
When running dataLoaderCLUS with rsfCLUS module, throws an error (see below).  Issue appears to be at Line 518 of rsfCLUS.R

**To Reproduce**
1. Run the dataloaderCLUS on Tyler's machine with rsfCLUS module

2. Console error:
storing covariates in rsfcovar table
predicting RSF
Error in `[.data.table`(rsf_model_coeff, rsf == rsfPops[[1]][[i]], "minv") : 
  column(s) not found: minv

3. Traceback error:
12. stop("column(s) not found: ", paste(ansvars[is.na(ansvals)], collapse = ", "))
11. `[.data.table`(rsf_model_coeff, rsf == rsfPops[[1]][[i]], "minv") at rsfCLUS.R#518
10. rsf_model_coeff[rsf == rsfPops[[1]][[i]], "minv"] at rsfCLUS.R#518
9. predictRSF(sim) at rsfCLUS.R#63
8. get(moduleCall, envir = fnEnv)(sim, cur[["eventTime"]], cur[["eventType"]])
7. eval(fnCallAsExpr)
6. eval(fnCallAsExpr)
5. .runEvent(sim, cacheIt, debug, moduleCall, fnEnv, cur, notOlderThan)
4. doEvent(sim, debug = debug, notOlderThan = notOlderThan)
3. spades(mySim)
2. spades(mySim)
1. system.time({ mysimout <- spades(mySim) })

**Expected behavior**
Should run the datalaoderCLUS with rsfCLUS module.

**Comment by KyleLochhead** [comment]
Deprecate rsfCLUS?

**Comment by TylerMuhly** [comment]
> Deprecate rsfCLUS?

Yes
